### ISSUE TITLE
avoid importing non-PEM files as certificates

### ISSUE THREAD

**Issue by belforte** [vkuznet/gocurl#5]
when we need to specity -capath we will usually point to a directory like /etc/grid-security/certificates which contains a lot of non-PEM files as well. This currently leads to a lot of warning from https://github.com/vkuznet/gocurl/blob/47f0a476a1f6aec3fb69be54c315f07e149a3353/main.go#L231 resulting in a very long stdout where actual error messages may get lost (user just has to decide to ignore all that's written).

It may be better to only try to import files which declares themselves as `.pem` and only report in case one of such files has a wrong format. I presume that there's no way to get current /etc/grid-security/certificates directory format changed.

@ddaina FYI

**Comment by vkuznet** [comment]
Stefano, please try out new release (0.0.3) or use master head. I committed relevant change to the master. Let me know if it will fix your problem.

**Comment by belforte** [comment]
I usually use /cvmfs/cms.cern.ch/cmsmon/gocurl and could not find a way to make it tell which release/version it resolves to, anyhow it has not changed bheavior yet.  How do I make sure that I use 0.0.3 ? Do I need to run make myself from GH ?

**Comment by belforte** [comment]
ok. I checked out main (not master) from this repo and ran make
it did
 go: downloading github.com/vkuznet/x509proxy v0.0.0-20210801171832-e47b94db99b6
not v 0.0.3
anyhow spurios messages are gone with that

**Comment by vkuznet** [comment]
Stefano, you can easily grab executable for your favorite architecture from release page, see right side bar on github page and click on release. Anyway, I added explicitly `-version` flag to the tool such that you can easily find it out. Starting from 0.0.4 release it will be like:
```
./gocurl -version
gocurl git=0.0.3 go=go1.17.2 date=2021-02-12
```
So, it will tell you git tag, go compiler version and date when executable was compiled. I'll put changes into cvmfs shortly.

**Comment by belforte** [comment]
got it, thanks
